# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
